Suchleiste wird auf IOS Geräten fokussiert
kultursphaere-sh/kulturfinder.sh-frontend pull request #140
Opened 2024-06-05 17:58 UTC by nigina23

2024-07-05 14:52 UTC, tjorbo requested changes

2024-07-05 14:52 UTC, tjorbo commented on src/views/Dashboard.vue
> +      this.searchbarOpen = !this.searchbarOpen
@nigina23 können wir, um die Lesbarkeit zu erhöhen, das umschalten des Status hinter die Condition innerhalb des $nextTick setzen?

So wird searchbarOpen im aktuellen State vollständig verwendet und erst danach und im selben Tick wird der State geändert.

`
this.$nextTick =>..
  if () ....
  this.searchbarOpen = !this....
})
`

2024-07-29 13:49 UTC, nigina23 commented
es funktioniert nur wenn der toggle state außerhalb this.$nextTick(() => ist

2024-08-06 10:07 UTC, tjorbo approved these changes
Danke!

2024-08-06 10:07 UTC, tjorbo commented on src/views/Dashboard.vue
> +      this.searchbarOpen = !this.searchbarOpen
@nigina23 Ich habe verstanden, wieso du das so rum gebaut hast. Es scheint nicht anders möglich zu sein. Gute Arbeit!

2024-08-06 10:10 UTC, merged