refactor: create api service adapter out of institution service
kultursphaere-sh/kulturfinder.sh-frontend pull request #43
Opened 2023-10-17 08:22 UTC by tjorbo

To use different APIs, the institution-service will not know API specific information. Instead, there is an interface at the api-service with 2 calls. This is a preparation for a second api-service in a derivative kulturfinder.

2023-10-17 10:36 UTC, tradiscantia commented
![image](https://github.com/kultursphaere-sh/kulturfinder.sh-frontend/assets/133165059/e7d8532b-ac49-4866-8208-ff8a642ae180)
![image](https://github.com/kultursphaere-sh/kulturfinder.sh-frontend/assets/133165059/dc521c94-6f2e-4602-bb53-e86bd2513a43)
Bei den Änderungen ist was bei den Filtern und Tags falsch gelaufen

2023-10-17 11:53 UTC, tjorbo commented
@tradiscantia Danke für den Hinweis :) ist korrigiert

2023-10-17 12:28 UTC, tradiscantia requested changes
Die selben Änderungen müssen noch bei getHolidayNameById() angepasst werden

2023-10-19 16:23 UTC, tradiscantia approved these changes

2023-10-19 16:25 UTC, merged